/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import "AppDelegate.h"

#import "RCTRootView.h"

#import <objc/runtime.h>

@interface AwesomeProject1 : NSObject <RCTBridgeModule>

@end

AwesomeProject1 *ap1 = nil;

@implementation AwesomeProject1

- (void)dealloc
{
  NSLog(@"dealloc");
}

- (instancetype)init
{
  NSLog(@"init");
  self = [super init];
  return self;
}

RCT_EXPORT_MODULE()

RCT_EXPORT_METHOD(processString:(NSString *)input callback:(RCTResponseSenderBlock)callback)
{
  callback(@[@"Hello"]);
}

- (NSDictionary *)constantsToExport
{
  return @{ @"aaa": @"Monday" };
}

@end

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  Class moduleClass = [AwesomeProject1 class];
  unsigned int count;
  Method *methods = class_copyMethodList(object_getClass(moduleClass), &count);
  for (int i = 0; i < count; i++)
  {
    Method method = methods[i];
    SEL selector = method_getName(method);
    NSString *name = NSStringFromSelector(selector);
    //        if ([name hasPrefix:@"test"])
    NSLog(@"方法 名字 ==== %@",name);
    if (name)
    {
      //avoid arc warning by using c runtime
      //            objc_msgSend(self, selector);
    }
    
    //NSLog(@"Test '%@' completed successfuly", [name substringFromIndex:4]);
  }
  
  NSURL *jsCodeLocation;

  /**
   * Loading JavaScript code - uncomment the one you want.
   *
   * OPTION 1
   * Load from development server. Start the server from the repository root:
   *
   * $ npm start
   *
   * To run on device, change `localhost` to the IP address of your computer
   * (you can get this by typing `ifconfig` into the terminal and selecting the
   * `inet` value under `en0:`) and make sure your computer and iOS device are
   * on the same Wi-Fi network.
   */

  jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios&dev=true"];

  /**
   * OPTION 2
   * Load from pre-bundled file on disk. The static bundle is automatically
   * generated by the "Bundle React Native code and images" build step when
   * running the project on an actual device or running the project on the
   * simulator in the "Release" build configuration.
   */

//   jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"AwesomeProject"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];
  rootView.appProperties = @{@"aa": @"aa"};

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  UINavigationController *nv = [[UINavigationController alloc] initWithRootViewController:[UIViewController new]];
  [nv pushViewController:rootViewController animated:NO];
  self.window.rootViewController = nv;
  [self.window makeKeyAndVisible];
  return YES;
}

@end
